;;;;  HTML5 parser for Common Lisp
;;;;
;;;;  Copyright (C) 2020 Thomas Bakketun <thomas@bakketun.pro>
;;;;  Copyright (C) 2012 Asgeir Bjørlykke <asgeir@copyleft.no>
;;;;  Copyright (C) 2012 Mathias Hellevang
;;;;  Copyright (C) 2012 Stian Sletner <stian@copyleft.no>
;;;;
;;;;  This library is free software: you can redistribute it and/or modify
;;;;  it under the terms of the GNU Lesser General Public License as published
;;;;  by the Free Software Foundation, either version 3 of the License, or
;;;;  (at your option) any later version.
;;;;
;;;;  This library is distributed in the hope that it will be useful,
;;;;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;;;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;;;  GNU General Public License for more details.
;;;;
;;;;  You should have received a copy of the GNU General Public License
;;;;  along with this library.  If not, see <http://www.gnu.org/licenses/>.

(defpackage #:html5-parser/interface/tokenization-state
  (:export
   #:DATA-STATE
   #:RCDATA-STATE
   #:RAWTEXT-STATE
   #:SCRIPT-DATA-STATE
   #:PLAINTEXT-STATE
   #:TAG-OPEN-STATE
   #:END-TAG-OPEN-STATE
   #:TAG-NAME-STATE
   #:RCDATA-LESS-THAN-SIGN-STATE
   #:RCDATA-END-TAG-OPEN-STATE
   #:RCDATA-END-TAG-NAME-STATE
   #:RAWTEXT-LESS-THAN-SIGN-STATE
   #:RAWTEXT-END-TAG-OPEN-STATE
   #:RAWTEXT-END-TAG-NAME-STATE
   #:SCRIPT-DATA-LESS-THAN-SIGN-STATE
   #:SCRIPT-DATA-END-TAG-OPEN-STATE
   #:SCRIPT-DATA-END-TAG-NAME-STATE
   #:SCRIPT-DATA-ESCAPE-START-STATE
   #:SCRIPT-DATA-ESCAPE-START-DASH-STATE
   #:SCRIPT-DATA-ESCAPED-STATE
   #:SCRIPT-DATA-ESCAPED-DASH-STATE
   #:SCRIPT-DATA-ESCAPED-DASH-DASH-STATE
   #:SCRIPT-DATA-ESCAPED-LESS-THAN-SIGN-STATE
   #:SCRIPT-DATA-ESCAPED-END-TAG-OPEN-STATE
   #:SCRIPT-DATA-ESCAPED-END-TAG-NAME-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPE-START-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPED-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPED-DASH-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPED-DASH-DASH-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPED-LESS-THAN-SIGN-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPE-END-STATE
   #:BEFORE-ATTRIBUTE-NAME-STATE
   #:ATTRIBUTE-NAME-STATE
   #:AFTER-ATTRIBUTE-NAME-STATE
   #:BEFORE-ATTRIBUTE-VALUE-STATE
   #:|ATTRIBUTE-VALUE-(DOUBLE-QUOTED)-STATE|
   #:|ATTRIBUTE-VALUE-(SINGLE-QUOTED)-STATE|
   #:|ATTRIBUTE-VALUE-(UNQUOTED)-STATE|
   #:|AFTER-ATTRIBUTE-VALUE-(QUOTED)-STATE|
   #:SELF-CLOSING-START-TAG-STATE
   #:BOGUS-COMMENT-STATE
   #:MARKUP-DECLARATION-OPEN-STATE
   #:COMMENT-START-STATE
   #:COMMENT-START-DASH-STATE
   #:COMMENT-STATE
   #:COMMENT-LESS-THAN-SIGN-STATE
   #:COMMENT-LESS-THAN-SIGN-BANG-STATE
   #:COMMENT-LESS-THAN-SIGN-BANG-DASH-STATE
   #:COMMENT-LESS-THAN-SIGN-BANG-DASH-DASH-STATE
   #:COMMENT-END-DASH-STATE
   #:COMMENT-END-STATE
   #:COMMENT-END-BANG-STATE
   #:DOCTYPE-STATE
   #:BEFORE-DOCTYPE-NAME-STATE
   #:DOCTYPE-NAME-STATE
   #:AFTER-DOCTYPE-NAME-STATE
   #:AFTER-DOCTYPE-PUBLIC-KEYWORD-STATE
   #:BEFORE-DOCTYPE-PUBLIC-IDENTIFIER-STATE
   #:|DOCTYPE-PUBLIC-IDENTIFIER-(DOUBLE-QUOTED)-STATE|
   #:|DOCTYPE-PUBLIC-IDENTIFIER-(SINGLE-QUOTED)-STATE|
   #:AFTER-DOCTYPE-PUBLIC-IDENTIFIER-STATE
   #:BETWEEN-DOCTYPE-PUBLIC-AND-SYSTEM-IDENTIFIERS-STATE
   #:AFTER-DOCTYPE-SYSTEM-KEYWORD-STATE
   #:BEFORE-DOCTYPE-SYSTEM-IDENTIFIER-STATE
   #:|DOCTYPE-SYSTEM-IDENTIFIER-(DOUBLE-QUOTED)-STATE|
   #:|DOCTYPE-SYSTEM-IDENTIFIER-(SINGLE-QUOTED)-STATE|
   #:AFTER-DOCTYPE-SYSTEM-IDENTIFIER-STATE
   #:BOGUS-DOCTYPE-STATE
   #:CDATA-SECTION-STATE
   #:CDATA-SECTION-BRACKET-STATE
   #:CDATA-SECTION-END-STATE
   #:CHARACTER-REFERENCE-STATE
   #:NAMED-CHARACTER-REFERENCE-STATE
   #:AMBIGUOUS-AMPERSAND-STATE
   #:NUMERIC-CHARACTER-REFERENCE-STATE
   #:HEXADECIMAL-CHARACTER-REFERENCE-START-STATE
   #:DECIMAL-CHARACTER-REFERENCE-START-STATE
   #:HEXADECIMAL-CHARACTER-REFERENCE-STATE
   #:DECIMAL-CHARACTER-REFERENCE-STATE
   #:NUMERIC-CHARACTER-REFERENCE-END-STATE
   ))
