(in-package #:html5-parser)

(defpackage :html5-parser-tokenizer-state
  (:import-from
   :common-lisp
   *
   <
   =
   and
   case
   cond
   eql
   if
   incf
   let
   not
   or
   otherwise
   progn
   setf
   t
   unless
   when
   )

  (:import-from
   :html5-parser
   ASCII_alpha
   ASCII_alphanumeric
   ASCII_digit
   ASCII_hex_digit
   ASCII_lower_alpha
   ASCII_lower_hex_digit
   ASCII_upper_alpha
   ASCII_upper_hex_digit
   Anything_else
   adjusted-current-node-not-in-HTML-namespace-p
   anything_else-clause
   ascii-alphanumeric-p
   ascii-whitespace-p
   character-reference-code
   check-for-duplicate-attribute
   consume-next-input-character
   consume-those-characters
   consumed-as-part-of-an-attribute-p
   control-p
   create-new-attribute
   create-new-comment-token
   create-new-doctype-token
   create-new-end-tag-token
   create-new-start-tag-token
   current-attribute-name-append
   current-attribute-value-append
   current-character-case
   current-input-character
   current-token-appropriate-end-tag-p
   current-token-data-append
   current-token-name-append
   current-token-public-id-append
   current-token-set-force-quirks-flag
   current-token-set-public-id-not-missing
   current-token-set-self-closing-flag
   current-token-set-system-id-not-missing
   current-token-system-id-append
   define-state
   emit-character-token
   emit-character-tokens-from-temporary-buffer
   emit-current-token
   emit-end-of-file-token
   entity-matched-p
   flush-code-points-consumed-as-a-character-reference
   lowercase-version-of
   next-input-character
   noncharacter-p
   numeric-version-of-current-input-character
   peek-next-input-character
   reconsume-in
   reconsume-in-return-state
   set-return-state
   surrogate-p
   switch-state
   switch-to-the-return-state
   temporary-buffer-append
   temporary-buffer-append-code-point
   temporary-buffer-append-entity
   temporary-buffer-append-matched-character-reference
   temporary-buffer-clear
   temporary-buffer-equal
   this-is-a-parse-error
   with-matched-named-character-reference
   with-peek-next-input-character

   attribute-value-\(double-quoted\)-state
   attribute-value-\(single-quoted\)-state
   attribute-value-\(unquoted\)-state
   data-state

   ;; Constants
   EOF
   U+0000_NULL
   U+0009_CHARACTER_TABULATION
   U+000A_LINE_FEED
   U+000C_FORM_FEED
   U+0020_SPACE
   U+0021_EXCLAMATION_MARK_!
   U+0022_QUOTATION_MARK_\"
   U+0023_NUMBER_SIGN_\#
   U+0026_AMPERSAND_&
   U+0027_APOSTROPHE_\'
   U+002D_HYPHEN-MINUS_-
   U+002F_SOLIDUS_/
   U+003B_SEMICOLON_\;
   U+003C_LESS-THAN_SIGN_<
   U+003D_EQUALS_SIGN_=
   U+003E_GREATER-THAN_SIGN_>
   U+003F_QUESTION_MARK_?
   U+0058_LATIN_CAPITAL_LETTER_X
   U+005B_LEFT_SQUARE_BRACKET_[
   U+005D_RIGHT_SQUARE_BRACKET_]
   U+0060_GRAVE_ACCENT_\`
   U+0061_LATIN_SMALL_LETTER_A
   U+0062_LATIN_SMALL_LETTER_B
   U+0063_LATIN_SMALL_LETTER_C
   U+0064_LATIN_SMALL_LETTER_D
   U+0065_LATIN_SMALL_LETTER_E
   U+0069_LATIN_SMALL_LETTER_I
   U+006C_LATIN_SMALL_LETTER_L
   U+006D_LATIN_SMALL_LETTER_M
   U+006F_LATIN_SMALL_LETTER_O
   U+0070_LATIN_SMALL_LETTER_P
   U+0073_LATIN_SMALL_LETTER_S
   U+0074_LATIN_SMALL_LETTER_T
   U+0075_LATIN_SMALL_LETTER_U
   U+0078_LATIN_SMALL_LETTER_X
   U+0079_LATIN_SMALL_LETTER_Y
   U+FFFD_REPLACEMENT_CHARACTER
   )

  (:export
   #:DATA-STATE
   #:RCDATA-STATE
   #:RAWTEXT-STATE
   #:SCRIPT-DATA-STATE
   #:PLAINTEXT-STATE
   #:TAG-OPEN-STATE
   #:END-TAG-OPEN-STATE
   #:TAG-NAME-STATE
   #:RCDATA-LESS-THAN-SIGN-STATE
   #:RCDATA-END-TAG-OPEN-STATE
   #:RCDATA-END-TAG-NAME-STATE
   #:RAWTEXT-LESS-THAN-SIGN-STATE
   #:RAWTEXT-END-TAG-OPEN-STATE
   #:RAWTEXT-END-TAG-NAME-STATE
   #:SCRIPT-DATA-LESS-THAN-SIGN-STATE
   #:SCRIPT-DATA-END-TAG-OPEN-STATE
   #:SCRIPT-DATA-END-TAG-NAME-STATE
   #:SCRIPT-DATA-ESCAPE-START-STATE
   #:SCRIPT-DATA-ESCAPE-START-DASH-STATE
   #:SCRIPT-DATA-ESCAPED-STATE
   #:SCRIPT-DATA-ESCAPED-DASH-STATE
   #:SCRIPT-DATA-ESCAPED-DASH-DASH-STATE
   #:SCRIPT-DATA-ESCAPED-LESS-THAN-SIGN-STATE
   #:SCRIPT-DATA-ESCAPED-END-TAG-OPEN-STATE
   #:SCRIPT-DATA-ESCAPED-END-TAG-NAME-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPE-START-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPED-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPED-DASH-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPED-DASH-DASH-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPED-LESS-THAN-SIGN-STATE
   #:SCRIPT-DATA-DOUBLE-ESCAPE-END-STATE
   #:BEFORE-ATTRIBUTE-NAME-STATE
   #:ATTRIBUTE-NAME-STATE
   #:AFTER-ATTRIBUTE-NAME-STATE
   #:BEFORE-ATTRIBUTE-VALUE-STATE
   #:|ATTRIBUTE-VALUE-(DOUBLE-QUOTED)-STATE|
   #:|ATTRIBUTE-VALUE-(SINGLE-QUOTED)-STATE|
   #:|ATTRIBUTE-VALUE-(UNQUOTED)-STATE|
   #:|AFTER-ATTRIBUTE-VALUE-(QUOTED)-STATE|
   #:SELF-CLOSING-START-TAG-STATE
   #:BOGUS-COMMENT-STATE
   #:MARKUP-DECLARATION-OPEN-STATE
   #:COMMENT-START-STATE
   #:COMMENT-START-DASH-STATE
   #:COMMENT-STATE
   #:COMMENT-LESS-THAN-SIGN-STATE
   #:COMMENT-LESS-THAN-SIGN-BANG-STATE
   #:COMMENT-LESS-THAN-SIGN-BANG-DASH-STATE
   #:COMMENT-LESS-THAN-SIGN-BANG-DASH-DASH-STATE
   #:COMMENT-END-DASH-STATE
   #:COMMENT-END-STATE
   #:COMMENT-END-BANG-STATE
   #:DOCTYPE-STATE
   #:BEFORE-DOCTYPE-NAME-STATE
   #:DOCTYPE-NAME-STATE
   #:AFTER-DOCTYPE-NAME-STATE
   #:AFTER-DOCTYPE-PUBLIC-KEYWORD-STATE
   #:BEFORE-DOCTYPE-PUBLIC-IDENTIFIER-STATE
   #:|DOCTYPE-PUBLIC-IDENTIFIER-(DOUBLE-QUOTED)-STATE|
   #:|DOCTYPE-PUBLIC-IDENTIFIER-(SINGLE-QUOTED)-STATE|
   #:AFTER-DOCTYPE-PUBLIC-IDENTIFIER-STATE
   #:BETWEEN-DOCTYPE-PUBLIC-AND-SYSTEM-IDENTIFIERS-STATE
   #:AFTER-DOCTYPE-SYSTEM-KEYWORD-STATE
   #:BEFORE-DOCTYPE-SYSTEM-IDENTIFIER-STATE
   #:|DOCTYPE-SYSTEM-IDENTIFIER-(DOUBLE-QUOTED)-STATE|
   #:|DOCTYPE-SYSTEM-IDENTIFIER-(SINGLE-QUOTED)-STATE|
   #:AFTER-DOCTYPE-SYSTEM-IDENTIFIER-STATE
   #:BOGUS-DOCTYPE-STATE
   #:CDATA-SECTION-STATE
   #:CDATA-SECTION-BRACKET-STATE
   #:CDATA-SECTION-END-STATE
   #:CHARACTER-REFERENCE-STATE
   #:NAMED-CHARACTER-REFERENCE-STATE
   #:AMBIGUOUS-AMPERSAND-STATE
   #:NUMERIC-CHARACTER-REFERENCE-STATE
   #:HEXADECIMAL-CHARACTER-REFERENCE-START-STATE
   #:DECIMAL-CHARACTER-REFERENCE-START-STATE
   #:HEXADECIMAL-CHARACTER-REFERENCE-STATE
   #:DECIMAL-CHARACTER-REFERENCE-STATE
   #:NUMERIC-CHARACTER-REFERENCE-END-STATE
   ))
