(defpackage #:html5-parser/tokenization-dsl
  (:use
   #:html5-parser/unicode-constants
   #:html5-parser/infra
   #:html5-parser/tokenization-state
   )
  (:import-from #:html5-parser/parser-state
                #:this-is-a-parse-error)
  (:import-from #:common-lisp
                #:*
                #:<
                #:=
                #:and
                #:case
                #:cond
                #:eql
                #:if
                #:incf
                #:let
                #:not
                #:or
                #:otherwise
                #:progn
                #:setf
                #:t
                #:unless
                #:when
                )
  (:export
   #:adjusted-current-node-not-in-HTML-namespace-p
   #:ASCII_alpha
   #:ASCII_alphanumeric
   #:ASCII_digit
   #:ASCII_hex_digit
   #:ASCII_lower_alpha
   #:ASCII_lower_hex_digit
   #:ASCII_upper_alpha
   #:ASCII_upper_hex_digit
   #:Anything_else
   #:anything_else-clause
   #:ascii-alphanumeric-p
   #:ascii-whitespace-p
   #:character-reference-code
   #:check-for-duplicate-attribute
   #:consume-next-input-character
   #:consume-those-characters
   #:consumed-as-part-of-an-attribute-p
   #:control-p
   #:create-new-attribute
   #:create-new-comment-token
   #:create-new-doctype-token
   #:create-new-end-tag-token
   #:create-new-start-tag-token
   #:current-attribute-name-append
   #:current-attribute-value-append
   #:current-character-case
   #:current-input-character
   #:current-token-appropriate-end-tag-p
   #:current-token-data-append
   #:current-token-name-append
   #:current-token-public-id-append
   #:current-token-set-force-quirks-flag
   #:current-token-set-public-id-not-missing
   #:current-token-set-self-closing-flag
   #:current-token-set-system-id-not-missing
   #:current-token-system-id-append
   #:define-state
   #:emit-character-token
   #:emit-character-tokens-from-temporary-buffer
   #:emit-current-token
   #:emit-end-of-file-token
   #:flush-code-points-consumed-as-a-character-reference
   #:lowercase-version-of
   #:matched-named-character-reference
   #:next-input-character
   #:noncharacter-p
   #:numeric-version-of-current-input-character
   #:peek-next-input-character
   #:reconsume-in
   #:reconsume-in-return-state
   #:set-return-state
   #:surrogate-p
   #:switch-state
   #:switch-to-the-return-state
   #:temporary-buffer-append
   #:temporary-buffer-append-code-point
   #:temporary-buffer-append-matched-named-character-reference
   #:temporary-buffer-clear
   #:temporary-buffer-equal
   #:this-is-a-parse-error
   #:with-matched-named-character-reference
   #:with-peek-next-input-character

   ;; Constants
   #:EOF
   ))
